version: "3.9"

services:
  postgres:
    image: postgres:15
    env_file:
      - ./.env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./packages/backend
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    volumes:
      - ./packages/backend/src:/app/src
    depends_on:
      - postgres

  frontend:
    build: ./packages/frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./packages/frontend/src:/app/src

volumes:
  db-data:
